/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Clinical / Patient Light Surface Palette
        "surface-base": "#F8FAFC",
        "surface-card": "#FFFFFF",
        "surface-nested": "#F1F5F9",
        "surface-bright": "#F8F9FF",
        "surface-variant": "#D3E4FE",
        "border-grid": "#E2E8F0",
        "border-strong": "#CBD5E1",
        "text-primary": "#0F172A",
        "text-secondary": "#475569",
        "text-muted": "#64748B",

        // Radiologist PACS Viewer Dark Palette
        "dicom-canvas": "#070A0F",
        "dicom-surface": "#0F172A",
        "dicom-border": "#1E293B",
        "dicom-text-primary": "#F8FAFC",
        "dicom-text-secondary": "#94A3B8",

        // Clinical Accent & Primary Tones
        "primary": "#0F172A",
        "on-primary": "#FFFFFF",
        "primary-container": "#131B2E",
        "on-primary-container": "#7C839B",
        "secondary": "#006781",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#8FDFFF",
        "on-secondary-container": "#00647D",
        "secondary-fixed": "#B9EAFF",
        "secondary-fixed-dim": "#81D1F0",
        "audit-hash": "#334155",

        // Clinical State & Tamper Verification Tokens
        "status-verified": "#059669",
        "status-verified-bg": "#ECFDF5",
        "status-verified-border": "#A7F3D0",
        "status-caution": "#D97706",
        "status-caution-bg": "#FFFBEB",
        "status-caution-border": "#FDE68A",
        "alert-tamper": "#DC2626",
        "alert-tamper-bg": "#FEF2F2",
        "alert-tamper-border": "#FCA5A5",
        "status-revoked": "#991B1B",
        "status-pending": "#2563EB",
        "status-pending-bg": "#EFF6FF",
        "status-pending-border": "#BFDBFE",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "0.75rem",
        "margin": "1rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "code-hash": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "code-hash": ["11px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
